# Generated by Django 4.2.6 on 2023-10-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sistema_integrado_notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='grupo_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
