# Generated by Django 4.2.6 on 2023-10-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_integrado_notificaciones', '0002_entidad_grupo_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
