# Generated by Django 4.2.6 on 2023-10-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_integrado_notificaciones', '0003_alter_entidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
