# Generated by Django 4.2.6 on 2023-10-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_integrado_notificaciones', '0004_alter_entidad_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='fecha_ultima_publicacion',
            new_name='fecha_ultima_modificacion',
        ),
    ]
